#!/usr/bin/env bash
#
#   (c) 2022 Ruan K. F <ruan.klein@gmail.com>
#   All Rights Reserved.
#
#   toolbox-shortcuts is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   toolbox-shortcuts is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with toolbox-shortcuts. If not, see <http://www.gnu.org/licenses/>.
#

### toolbox-shortcuts: cli utility

applicationroot="$(dirname "$(readlink -f "$0")")"

source "${applicationroot}/lib/helpers.sh"
source "${applicationroot}/lib/options.sh"

options=("create" "help")
exec=$(get_option "$1" ${options[*]})

$exec ${*:2}