#!/usr/bin/env python3

from os import path, readlink
from sys import argv

from lib.helpers import is_container, get_container_info
from lib.handler import run_as_native, run_as_container, run_as_cli

command = argv[0]

app_root = path.dirname(path.realpath(command))
command_name = path.basename(command)
container_name = path.basename(
    readlink(command)) if path.islink(command) else None

args = argv[1:]

if not container_name or container_name == 'toolbox-shortcuts-handler':
    return_code = run_as_cli(app_root, args)
    exit(return_code)

if is_container():
    running_container = get_container_info('name')

    if running_container == container_name:
        run_as_native(command_name, args)

run_as_container(command_name, container_name, args)
